### PR TITLE
Implements One-time API Key View/Copy 

### PR DESCRIPTION
**Pull request by Sharathxct**
### Summary
This PR adds more abstraction to API Key where users can retrieve or access their API Key only once which is at generation. as mentioned in #343 .

### Description
Changed UI components/Dashboard:
-ApiKey.js (New Component to show api key)
-ApikeyTable.js (Removed API key column)
-Dashboard.js 
Changed backend controllers:
-fetchKeysByuserid (Modified to not respond with api keys ) 

### How to Test the Changes
Login and generate a new API key 

### Screenshots or Recordings (Optional)
screenshot_000

https://github.com/user-attachments/assets/a3ca6a2f-e11e-4b84-8279-d06e7c26fbe9

## Checklist
- [✅] I have tested the changes locally and they work as expected.
- [✅] I have added/updated tests that cover the changes.
- [✅] I have updated the documentation to reflect the changes.
- [✅] This pull request follows the project's coding guidelines.

### CODE REVIEW

**Review by amankumarsingh77 — CHANGES_REQUESTED** [review]
Post the test coverage screenshot.

**Comment by Sharathxct** [comment]
Test coverage client:
client1
client2

Test coverage server:
server1
server2

**Comment by amankumarsingh77** [comment]
@aps08 There seem to be some conflicts. Probably with the `services/Keys`.

**Comment by aps08** [comment]
@Sharathxct resolve the conflict. It is a few minutes task and it's getting dragged for days. Not good.

**Comment by Sharathxct** [comment]
@aps08 Sorry conflicts resolved now

**Review by aps08 — APPROVED** [review]

**Pull request merged**
