### PR TITLE
Add Bug Report Form

### LINKED ISSUE #335: Add Bug Report Form
### What is this issue related to?

Enhancement

### Description

We need to add a bug report form to improve our issue management process. This will help streamline bug reporting and make it easier for maintainers to triage and address issues efficiently.

### Expected Behavior

_No response_

### Current Behavior

_No response_

### Additional Information (optional)

_No response_

### Confirmation Checklist

- [X] I have searched for similar issues before creating this one.
- [X] I have provided all the necessary information to understand and reproduce the issue.

### PR DESCRIPTION
**Pull request by VinayakaHegade**
### Summary

Added a new bug report form template and disabled blank issues.

### Description
closes #335 
- Created a new bug_form.yml file in .github/ISSUE_TEMPLATE/ directory
- Disabled blank issues by adding config.yml to the ISSUE_TEMPLATE directory

### How to Test the Changes
We can see it live in this repository only after merging these changes. For testing you can copy the files and add it to your personal repos and test it.

### Screenshots or Recordings (Optional)
preview
bug_form

## Checklist

- [x] I have tested the changes locally and they work as expected.
- [ ] I have added/updated tests that cover the changes.
- [ ] I have updated the documentation to reflect the changes.
- [x] This pull request follows the project's coding guidelines.

### CODE REVIEW

**Review by aps08 — CHANGES_REQUESTED** [review]
Add one more label as  "high priority". I think it is available.

**Comment by VinayakaHegade** [comment]
> Add one more label as "high priority". I think it is available.

Added high priority label.

**Comment by aps08** [comment]
> > Add one more label as "high priority". I think it is available.
> 
> Added high priority label.

Add the updated screenshot

**Comment by VinayakaHegade** [comment]
> > > Add one more label as "high priority". I think it is available.
> > 
> > 
> > Added high priority label.
> 
> Add the updated screenshot

@aps08 Added 
issue-form-with-labels

**Pull request merged**
