### PR TITLE
Raise Request (backend)

### PR DESCRIPTION
**Pull request by computeronaldo**
### Summary
- This PR implements the Raise a Request feature that allows logged in users to submit a form when they cannot find a company logo. The form collects the company URL, which are validated before submission.

#370 

### Approach

1. **Mongoose Model Creation**:
   - Developed a Mongoose model for the `RaiseRequest` document to facilitate the storage of user requests in the **RaiseRequest** collection. This model defines the schema and data types for the required fields, ensuring data integrity.

2. **API Route Implementation**:
   - Implemented the API route at `/api/user/logo-request` to handle incoming requests from the frontend. This route is responsible for processing the user’s logo request submissions.

3. **Controller and Service Development**:
   - Wrote the corresponding controller to manage the logic for processing requests, validating user input, and interacting with the Mongoose model.
   - Created a service layer to encapsulate the business logic related to logo requests, improving code organization and reusability.

4. **Testing**:
   - Developed comprehensive test cases for the backend functionality to ensure that the API route, controller, and service work as expected. These tests validate the handling of various scenarios, including successful submissions and error handling for invalid inputs.

### How to Test the Changes

- **Start client and server with `yarn start`.**
- Hit the endpoint `/api/user/logo-request` with a company URL and userId in request body. And you can expect response as shown in the below screenshot.

Screenshot (257)

### Screenshots or Recordings

[screen-capture (1).webm](https://github.com/user-attachments/assets/a7a20533-50f6-4922-bb55-637a80a5be7a)

### Code Coverage Report

Screenshot (258)
Screenshot (259)
Screenshot (260)
Screenshot (261)

## Checklist

- ✅ I have added/updated tests that cover the changes.
- ✅ I have passed all testcases (server).

### CODE REVIEW

**Comment by aps08** [comment]
Still showing 21 file changes.

**Review by amankumarsingh77 — APPROVED** [review]
Everything looks good to me in the server section. Make sure to not make small changes like spaces and new lines. 
Please avoid `git add .` Review your changes and push only after checks.

**Comment by computeronaldo** [comment]
> Still showing 21 file changes.

Hey @aps08 most of the changes are in backend and as for changes in frontend can be pushed here they won't cause any issue or if you want I can discard them and when @shantanu-02 pushes his code (along with testcases for frontend), those changes will be reflected there.

**Comment by computeronaldo** [comment]
Hi @aps08, downgraded vitest to it's correct version 2.0.5, also I removed yarn.lock file from my PR. And let me know if you want me to keep frontend changes in this PR or not? Keeping those frontend changes aren't going to cause any issues but if you want I can discard them in this PR. Also when @shantanu-02 will be raising his PR for frontend testcases those changes on frontend can be merged at that time. So tell me know how you want this to go. Also I am modifying this PR to include issue number but I won't be setting it so that it fixes the issue if this PR is merged as only after @shantanu-02 's changes issue can be considered fixed.

**Review by aps08 — CHANGES_REQUESTED** [review]
remove frontend files

**Comment by computeronaldo** [comment]
> remove frontend files

Hi @aps08 I have removed all the frontend files, this branch now contains only backend changes. Let me know in case you want further changes.

**Review by aps08 — APPROVED** [review]

**Pull request merged**
