### PR TITLE
Refactor Admin controller: Implement Repository Pattern and Update Routes for Monorepo

### PR DESCRIPTION
**Pull request by DeltaDynamo**
# Summary

This PR refactors the `Admin Controllers` and `Services` to implement the Repository Pattern, improving code organization, maintainability, and scalability. It also updates the routing structure for managing admin-specific operations, such as adding administrators, managing uploaded images, and handling file re-uploads.

---

# Approach

### Refactor to Repository Pattern
- Shifted data access logic from controllers to dedicated repository classes.
- Refactored services to delegate database interactions to repositories, adhering to the principle of separation of concerns.
- Replaced direct database queries in controllers with service-layer methods for improved modularity.

---

### Refactored Admin Controllers & Updated API Endpoints

The following endpoints have been updated and aligned with the repository pattern:

- **PUT `/api/admin/add`**: Endpoint for adding new administrators.
- **GET `/api/admin/images`**: Endpoint for retrieving image data uploaded by admins.
- **POST `/api/admin/upload`**: Endpoint for uploading new images.
- **PUT `/api/admin/reupload`**: Endpoint for re-uploading files securely.

---

### Monorepo Alignment
- Structured admin-related logic into services and repositories for better codebase modularity.
- Updated route definitions to conform to the monorepo setup and ensure consistency.

---

### Screenshots or Recordings
image
upload
reupload

## Checklist

- [ ] I have added/updated tests that cover the changes.
- [ ] I have updated the documentation to reflect the changes.

### CODE REVIEW

**Comment by aps08** [comment]
What is the progress on this ? @amoghar29

**Comment by amoghar29** [comment]
Only testing of reupload functionality is pending. On it. Will finish it by eod mostly.

**Comment by DeltaDynamo** [comment]
@aps08 PR is ready to merge.

**Comment by aps08** [comment]
@amoghar29 the documentation is incomplete. I am still merging it as we will have it reviewed sometime later.

**Pull request merged**
