### PR TITLE
New footer component

### PR DESCRIPTION
**Pull request by 001AM**
### Summary

This PR implements the Footer Component on the pages as per the new design.
Issue : https://github.com/TeamShiksha/logoexecutive/issues/445

### How to Test the Changes
To test the changes you have to render the pages to check footer component rendering.

### Screenshots or Recordings
Expected UI :
Footer
Footer
Implemented Recording:

https://github.com/user-attachments/assets/c43ab05f-f5fa-42f3-8b44-ee4bdd6af83d

## Checklist

- [x] I have added/updated tests that cover the changes.
- [x] I have updated the documentation to reflect the changes.

### CODE REVIEW

**Comment by aps08** [comment]
@Ayushsanjdev review this properly by EOD.

**Comment by aps08** [comment]
I will let you know the title of the links during the call and you can edit it.

**Comment by 001AM** [comment]
ok

**Comment by 001AM** [comment]
- Changing the Navigation in footer.
- Changing the header color.
- Adding the branding.

**Comment by aps08** [comment]
@001AM when you make changes to code, then you also have to update the screenshot/recording

**Comment by 001AM** [comment]
@aps08 Updated the recording

**Review by aps08 — APPROVED** [review]

**Pull request merged**
