### PR TITLE
add: more issue templates

### LINKED ISSUE #391: Add more issue templates for different items
### What is this issue related to?

Documentation

### Description

To improve the issue reporting process, additional templates needs to be added for documentation issues and other category. These templates will improve the submission process, making it easier for people to contribute to projects.

### Expected Behavior

New issue templates are added to the repository for documentation and other category.

### Current Behavior

The repository only have templates for bug reporting and pull requests.

### Additional Information (optional)

No response.

### Confirmation Checklist

- [x] I have searched for similar issues before creating this one.
- [x] I have provided all the necessary information to understand and reproduce the issue.

### PR DESCRIPTION
**Pull request by ayush19sinha**
### Summary

This PR adds new issue templates for documentation related issues and other category.

### Approach

Previously, contributors were only presented with a single issue template, which often caused confusion when reporting issues. This also made it difficult for maintainers to prfioritize and address the most critical issues. With this update, contributors will now have the option to directly raise documentation issues or other types of issues, streamlining the issue reporting process and improving overall project management.

Issue ticket number : https://github.com/TeamShiksha/logoexecutive/issues/391

### How to Test the Changes

To test these changes, navigate to the repository's "New Issue" page and verify that the options for "Documentation Issue" and "Other Issue" are available and function as expected

### Screenshots or Recordings

documentation new
Other issue

## Checklist

- [x] I have added/updated tests that cover the changes.
- [x] I have updated the documentation to reflect the changes.

### CODE REVIEW

**Comment by Ayushsanjdev** [comment]
From where did u took reference?

**Comment by ayush19sinha** [comment]
I looked up a few repositories but didn’t find any specific templates for the documentation issue and other issues. So, I implemented them based on the discussion in the meeting and the pattern of other issue templates in this repository.

**Comment by aps08** [comment]
> I looked up a few repositories but didn’t find any specific templates for the documentation issue and other issues. So, I implemented them based on the discussion in the meeting and the pattern of other issue templates in this repository.

Please mention the few repositories you looks into.

**Comment by ayush19sinha** [comment]
These are among few repositories I looked into which had good issue or pull request templates but didn't had any templates for documentation issue and other issue --

https://github.com/theos/theos
https://github.com/ankidroid/Anki-Android
https://github.com/Urigo/angular-meteor
https://github.com/CircuitVerse/CircuitVerse
https://github.com/stevemao/github-issue-templates

**Review by aps08 — APPROVED** [review]

**Pull request merged**
